#+TITLE: Notes on Measure Theoretic Probability Theory
#+AUTHOR: Reid Chen
#+EMAIL: reid.chen@wisc.edu
#+OPTIONS: email:t
#+LATEX_HEADER: \input{header.tex}

\begin{abstract}
This is a graduate course on probability theory, a mathematical study of random phenomena
It is a rigorous measure-theoretic apporach for probability, with no background needed on measure theory.
\end{abstract}

* Probability Spaces
** Measurable Spaces
*** Random Experiment
\begin{definition}[Random experiment] 
A random experiment is an experiment whose outcome is uncertain in the sense that it cannot be determined before the experiment is performed.
\end{definition}
\begin{definition}[Sample space]
The set of all possible outcomes in a random experiment is called the sample space of the experiment, denoted usually by $\Omega$.
\end{definition}

An outcome of the sample space is denoted by $\omega \in \Omega$.

**** Throwing a Die

There are 6 possible outcomes when we throw a die. Therefore, the sample space contains six elements. If we use numbers 1 to 6 to denote the numbers on the faces of a die, then the sample spaces
$$
\Omega = \{1, 2, 3, 4, 5, 6\}.
$$
Of course, you do not need to constraint yourself from using the numbers. You can also replace the numbers with the faces of a die. Note that the sample space $\Omega$ we have here is finite.

**** Bacteria Population

Suppose you have a petridish in which you grow bacteria. We wait for a day for the bacteria to form a population. The outcome is then the size of the population. The sample space would be
$$
\Omega = \{0, 1, 2, \dots\} = \mathbb{Z}_+.
$$
Note that this set is infinite and countable.

**** Motion on a Line

Suppose you have a line $\mathbb{R}$ and you have a person moving randomly on the line. Let the person moves for an hour. Where does the person stand when you are back?
The outcome in this case is the position of the bee. So, the sample space is $\mathbb{R}$.

**** Tossing a Coin Once

$$
\Omega = \{\text{H}, \text{T}\}.
$$

**** Tossing a Coin Five Times

$$
\Omega = \{\omega = (\omega_1, \dots, \omega_5) \mid \omega_i \in \{\text{H}, \text{T}\} \}.
$$
Each $\omega$ is a finite sequence, a 5-tuple.

**** Tossing a Coin Forever

$$
\Omega = \{ \omega = (\omega_1, \omega_2, \dots) = (\omega_i)_{i \in \mathbb{N}} \mid \omega_i \in \{\text{H}, \text{T}\} \}
$$
Each $\omega$ is an (infinite) sequence. $\Omega$ is uncountable.

*** Countable vs. Uncountable Set

\begin{definition}[Countable]
A set $A$ is called countably infinite if there is a bijection
$$
f: \mathbb{N} \to A,
$$
where $\mathbb{N} = \{1, 2, 3, \dots \}$.
\end{definition}

Here are some countable sets:

\begin{itemize}
\item $\mathbb{Z} = \{\dots, -3, -2, -1, 0, 1, 2, 3, \dots \}$
\item $\mathbb{N} ^ 2 = \{(n_1, n_2) \mid n_1, n_2 \in \mathbb{N} \}$
\item $\mathbb{Q} = \{ \frac{a}{b} \mid a, b \in \mathbb{Z}, b \ne 0 \}$
\item $A^n$
\end{itemize}

Here are some uncountable sets:

\begin{itemize}
\item $\mathbb{R}$
\item $\mathbb{R} \setminus \mathbb{Q}$
\end{itemize}
That is, they are infinite but not countably infinite.

*** Events


Informally speaking, an event is a statement about a random experiment whose truth is determined once the experiment is performed.
More formally, an event can be defined as the set of all outcomes in the sample space for which the statement holds true.
Mathematically, an event is a subset of the sample space:
$$
A \subset \Omega.
$$

How to decide if an event $A$ occur or not:
\begin{itemize}
\item perform the experiment
\item look at the outcome $\omega$
\item check if $\omega \in A$
\item If $\omega \in A$, we say that $A$ has occured
\item If $\omega \notin A$, we say that $A$ has not occured
\end{itemize}

**** Die

The sample space is $\Omega =\{1, 2, 3, 4, 5, 6\}$. Let $A$ be the event that we see a prime number. That is, $A = \{ 2, 3, 5\}$.

**** Bottle of Milk

Suppose in the beginning you have one liter of milk and your roommate drinks some of it. We would like to know the amount of milk left.
The sample space here is $\Omega = [0, 1]$. Let $A$ be the event that you have more than half of the bottle. Then, $A = (0.5, 1]$, which is an uncountable set.

**** Observing the Price of a Stock

If you are interested in the behavior of the price during a day, then an outcome is a continuous function that maps time to price.
Now, the $\Omega$ is the set of all continuous functions from time to price. An event $A$ can be: the price hits the price level 5 at least once:
$$
A = \{\omega \in \Omega \mid \omega(t) = 5 \text{ for some } t\}.
$$

*** Probability

Let $2^\Omega$ denote the set of all subsets of $\Omega$ (the power set of $\Omega$). We define probability as a function on the set of all events.
For infinite sets, especially when $\Omega$ is uncountable, $2^\Omega$ is too big as the "right" collection of all events.
Too big here means that it is mathematically inconvenient and has some uninteresting events.
Therefore, we restrict ourselves from $2^\Omega$ to a smaller collection, say $\mathcal{F}$, which is a collection of subsets of $\Omega$.
What properties should $\mathcal{F}$ satisfy?

\begin{itemize}
1. $\Omega \in \mathcal{F}$ (something happens)
2. $\emptyset \in \mathcal{F}$ (nothing happens)
3. $A \in \mathcal{F} \implies A^c \in \mathcal{F}$ (some statement happens, then the negative of this statement happens)
4. $A, B \in \mathcal{F} A \cup B \in \mathcal{F}, A \cap B \in \mathcal{F}$
\end{itemize}

* Random Variables
* Random Vectors
* Conditioning
* Infinite Collections of Random Variables
* Convergence
