#+TITLE: Notes on Measure Theoretic Probability Theory
#+AUTHOR: Reid Chen
#+EMAIL: reid.chen@wisc.edu
#+OPTIONS: email:t
#+LATEX_HEADER: \input{header.tex}

\begin{abstract}
This is a graduate course on probability theory, a mathematical study of random phenomena.
It is a rigorous measure-theoretic apporach for probability, with no background needed on measure theory.
\end{abstract}

* Probability Spaces
** Measurable Spaces
*** Random Experiment
\begin{definition}[Random experiment]
A random experiment is an experiment whose outcome is uncertain in the sense that it cannot be determined before the experiment is performed.
\end{definition}
\begin{definition}[Sample space]
The set of all possible outcomes in a random experiment is called the sample space of the experiment, denoted usually by $\Omega$.
\end{definition}

An outcome of the sample space is denoted by $\omega \in \Omega$.

**** Throwing a Die

There are 6 possible outcomes when we throw a die. Therefore, the sample space contains six elements. If we use numbers 1 to 6 to denote the numbers on the faces of a die, then the sample spaces
$$
\Omega = \{1, 2, 3, 4, 5, 6\}.
$$
Of course, you do not need to constraint yourself from using the numbers. You can also replace the numbers with the faces of a die. Note that the sample space $\Omega$ we have here is finite.

**** Bacteria Population

Suppose you have a petridish in which you grow bacteria. We wait for a day for the bacteria to form a population. The outcome is then the size of the population. The sample space would be
$$
\Omega = \{0, 1, 2, \dots\} = \mathbb{Z}_+.
$$
Note that this set is infinite and countable.

**** Motion on a Line

Suppose you have a line $\mathbb{R}$ and you have a person moving randomly on the line. Let the person moves for an hour. Where does the person stand when you are back?
The outcome in this case is the position of the bee. So, the sample space is $\mathbb{R}$.

**** Tossing a Coin Once

$$
\Omega = \{\text{H}, \text{T}\}.
$$

**** Tossing a Coin Five Times

$$
\Omega = \{\omega = (\omega_1, \dots, \omega_5) \mid \omega_i \in \{\text{H}, \text{T}\} \}.
$$
Each $\omega$ is a finite sequence, a 5-tuple.

**** Tossing a Coin Forever

$$
\Omega = \{ \omega = (\omega_1, \omega_2, \dots) = (\omega_i)_{i \in \mathbb{N}} \mid \omega_i \in \{\text{H}, \text{T}\} \}
$$
Each $\omega$ is an (infinite) sequence. $\Omega$ is uncountable.

*** Countable vs. Uncountable Set

\begin{definition}[Countable]
A set $A$ is called countably infinite if there is a bijection
$$
f: \mathbb{N} \to A,
$$
where $\mathbb{N} = \{1, 2, 3, \dots \}$.
\end{definition}

Here are some countable sets:

\begin{itemize}
\item $\mathbb{Z} = \{\dots, -3, -2, -1, 0, 1, 2, 3, \dots \}$
\item $\mathbb{N} ^ 2 = \{(n_1, n_2) \mid n_1, n_2 \in \mathbb{N} \}$
\item $\mathbb{Q} = \{ \frac{a}{b} \mid a, b \in \mathbb{Z}, b \ne 0 \}$
\item $A^n$
\end{itemize}

Here are some uncountable sets:

\begin{itemize}
\item $\mathbb{R}$
\item $\mathbb{R} \setminus \mathbb{Q}$
\end{itemize}
That is, they are infinite but not countably infinite.

*** Events


Informally speaking, an event is a statement about a random experiment whose truth is determined once the experiment is performed.
More formally, an event can be defined as the set of all outcomes in the sample space for which the statement holds true.
Mathematically, an event is a subset of the sample space:
$$
A \subset \Omega.
$$

How to decide if an event $A$ occur or not:
\begin{itemize}
\item perform the experiment
\item look at the outcome $\omega$
\item check if $\omega \in A$
\item If $\omega \in A$, we say that $A$ has occured
\item If $\omega \notin A$, we say that $A$ has not occured
\end{itemize}

**** Die

The sample space is $\Omega =\{1, 2, 3, 4, 5, 6\}$. Let $A$ be the event that we see a prime number. That is, $A = \{ 2, 3, 5\}$.

**** Bottle of Milk

Suppose in the beginning you have one liter of milk and your roommate drinks some of it. We would like to know the amount of milk left.
The sample space here is $\Omega = [0, 1]$. Let $A$ be the event that you have more than half of the bottle. Then, $A = (0.5, 1]$, which is an uncountable set.

**** Observing the Price of a Stock

If you are interested in the behavior of the price during a day, then an outcome is a continuous function that maps time to price.
Now, the $\Omega$ is the set of all continuous functions from time to price. An event $A$ can be: the price hits the price level 5 at least once:
$$
A = \{\omega \in \Omega \mid \omega(t) = 5 \text{ for some } t\}.
$$

*** $\sigma$ -algebra

Let $2^\Omega$ denote the set of all subsets of $\Omega$ (the power set of $\Omega$). We define probability as a function on the set of all events.
For infinite sets, especially when $\Omega$ is uncountable, $2^\Omega$ is too big as the "right" collection of all events.
Too big here means that it is mathematically inconvenient and has some uninteresting events.
Therefore, we restrict ourselves from $2^\Omega$ to a smaller collection, say $\mathcal{F}$, which is a collection of subsets of $\Omega$.
What properties should $\mathcal{F}$ satisfy?

\begin{itemize}
\item $\Omega \in \mathcal{F}$ (something happens)
\item $\emptyset \in \mathcal{F}$ (nothing happens)
\item $A \in \mathcal{F} \implies A^c \in \mathcal{F}$ (some statement happens, then the negative of this statement happens)
\item $A, B \in \mathcal{F} \implies A \cup B \in \mathcal{F}, A \cap B \in \mathcal{F}$
\end{itemize}

\begin{definition}[$\sigma$-algebra]
Let $\Omega$ be a nonempty set. A collection $\mathcal{F}$ of subsets of $\Omega$ is said to be a $\sigma$-algebra of $\Omega$ if it satisfies the following properties:
\begin{itemize}
\item $\Omega \in \mathcal{F}$,
\item $A \in \mathcal{F} \implies A^c \in \mathcal{F}$,
\item $A_1, A_2, \dots \in \mathcal{F} \implies \bigcup_{i \in \mathbb{N}} A_i \in \mathcal{F}$.
\end{itemize}
\end{definition}

\begin{definition}[Measurable space]
In the case where $\mathcal{F}$ is a $\sigma$-algebra of a nonempty set $\Omega$, $(\Omega, \mathcal{F})$ is called a measurable space.
\end{definition}

\begin{definition}[sub-$\sigma$-algebra]
If $\mathcal{G}$ is a $\sigma$-algebra on $\Omega$ with $\mathcal{G} \subset \mathcal{F}$, then $\mathcal{G}$ is called a sub-$\sigma$-algebra of $\mathcal{F}$.
\end{definition}

\begin{definition}[Measurable set]
If $(\Omega, \mathcal{F})$ is a measurable space. Each element of $\mathcal{F}$ is called a measruable set of $\mathcal{F}$-measurable set.
\end{definition}

Let $(\Omega, \mathcal{F})$ be a measurable space. We have the following propositions:

\begin{proposition}[$\emptyset$ is in $\mathcal{F}$]
$$
\emptyset \in \mathcal{F}.
$$
\end{proposition}

\begin{proof}
$\emptyset = \Omega^c \in \mathcal{F}$ since $\Omega \in \mathcal{F}$ by property 1 and $\mathcal{F}$ is closed under complement by property 2.
\end{proof}

\begin{proposition}[$\mathcal{F}$ is closed under finite unions]
$$
A_1, \dots, A_n \in \mathcal{F} \implies \bigcup_{i = 1}^{n} A_i \in \mathcal{F}.
$$
\end{proposition}

\begin{proof}
Let $A_{n + 1}, A_{n + 2}, \dots = \emptyset \in \mathcal{F}$ (by the previous proposition). Then, by property 3, we have $\bigcup_{i \in \mathcal{N}} A_i = \bigcup_{i=1}^n A_i \in \mathcal{F}$.
\end{proof}

\begin{proposition}[$\mathcal{F}$ is closed under countable intersections]
$$
A_1, A_2, \dots \in \mathcal{F} \implies \bigcap_{i \in \mathcal{N}} A_i \in \mathcal{F}.
$$
\end{proposition}

\begin{proof}
Note that
$$
\left(\bigcup_{i \in \mathcal{N}} A_i \right)^c = \left( \bigcap_{i \in \mathcal{N}} A_i^c \right).
$$
By property 3, the right hand side is in $\mathcal{F}$. Therefore, by 2, the complement of the left hand side is in $\mathcal{F}$.
\end{proof}

\begin{proposition}[$\mathcal{F}$ is closed under finite intersections]
$$
A_1, \dots A_n \in \mathcal{F} \implies \bigcap_{i = 1}^n A_i \in \mathcal{F}.
$$
\end{proposition}

\begin{proof}
\end{proof}

\begin{proposition}[$\mathcal{F}$ is closed under set differences]
$$
A, B \in \mathcal{F} \implies A \setminus B \in \mathcal{F}.
$$
\end{proposition}

\begin{proof}
\end{proof}

\begin{proposition}[$\mathcal{F}$ is closed under symmetric differences]
$$
A, B \in \mathcal{F} \implies (A \setminus B) \cup (B \setminus A) \in \mathcal{F}.
$$
\end{proposition}

\begin{proof}
\end{proof}

*** Generated $\sigma$ -algebra

Let $\Omega$ be a nonempty set. We know that $\mathcal{F} = 2^{\Omega}$ is the largest $\sigma$ -algebra on $\Omega$.
Every $\sigma$ -algebra is a sub- $\sigma$ -algebra of $\mathcal{F}$. $\mathcal{F}$ here is called discrete $\sigma$ -algebra.

Let $\mathcal{F} = \{\emptyset, \Omega\}$. It is known as the smallest $\sigma$ -algebra on $\Omega$, or the trivial $\sigma$ -algebra.

How about $\sigma$ -algebra in between these two? Or, let $\mathcal{A}$ be a nonempty collection of subsets of $\Omega$. What is the smallest $\sigma$ -algebra that contains all the sets in $\mathcal{A}$?

\begin{proposition}
The intersection of an arbitrary collection of $\sigma$-algebras on $\Omega$ is a $\sigma$-algebra on $\Omega$.
\end{proposition}

\begin{proof}
Let $I$ be an index set (countable or uncountable) and $\mathcal{F}_i$ a $\sigma$-algebra on $\Omega$ for each $i \in I$.
Let $\mathcal{F} = \bigcap_i \mathcal{F}_i$. We want to show that $\mathcal{F}$ is a $\sigma$-algebra on $\Omega$.
\begin{itemize}
\item $\Omega \in \mathcal{F}$ because $\Omega \in \mathcal{F}_i$ for each $i$.
\item Let $A \in \mathcal{F}$. So, $A \in \mathcal{F}_i$ for each $i$. By property 2, $A^c \in \mathcal{F}_i$ for each $i$. So, $A^c \in \mathcal{F}$.
\item Let $A_1, A_2, \dots \in \mathcal{F}$. So, $A_1, A_2, \dots in \mathcal{F}_i$ for all $i$. This means that, by property 3, that their intersection is in each $\mathcal{F}_i$. Hence, the intersection is in $\mathcal{F}$.
\end{itemize}
Hence, $\mathcal{F}$ is a $\sigma$-algebra.
\end{proof}

A consequence of this proposition is that given an arbitrary collection $\mathcal{A}$ of subsets of $\Omega$, the intersection of all $\sigma$ -algebra containing $\mathcal{A}$ is the smallest $\sigma$ -algebra containbing $\mathcal{A}$.
This is called the $\sigma$ -algebra generated by $\mathcal{A}$, denoted $\sigma(\mathcal{A})$:
$$
\sigma(\mathcal{A}) := \bigcap_{
    \mathcal{F} \text{ is a } \sigma \text{-algebra such that } \mathcal{A} \subset \mathcal{F}
} \mathcal{F}.
$$

Our interpretation for this is that $\mathcal{A}$ is the data (list of questions whose answers are directly provided). Then, we can answer more questions. The information generated by the data is $\sigma(\mathcal{A})$.

**** Bacteria Population

The sample space $\Omega$ in this example is $\mathbb{Z}_+$. Let $A_i$ be the event that there are $i$ individuals, that is, $A_i = \{ i \}$. Let $\mathcal{A} = \{ A_i \mid i \in \mathbb{Z}_+ \}$. What is the $\sigma$ -algebra generated by $\mathcal{A}$?
First of all, $\sigma(\mathcal{A}) \subset 2^{\mathbb{Z}_+}$. Actually, $\sigma(\mathcal{A}) = 2^{\mathbb{Z}_{+}}$.
To show this, we only need to show that $2^{\mathbb{Z}_+}$ is a subset of $\sigma(\mathcal{A})$. That is, we show
$$
A \in 2^{\mathbb{Z}_+} \implies A \in \sigma(\mathcal{A}).
$$
Since $\mathbb{Z}_+$ is countable, $A$ is countable. Write $A$ as
$$
\bigcup_{i \in A} \{ i \},
$$
which is a countable union. Note that by definiion, $\{i\} \in \mathcal{A}$. The countable union of elements in $\mathcal{A}$ is in $\sigma(\mathcal{A})$. Hence, $\sigma(\mathcal{A}) = 2^{\mathbb{Z}_+}$.

**** Tossing a Coin $n$ Times

The sample space is $\Omega = \{0, 1\}^n$. Let $A_i$ denote the event that the $i^\text{th}$ toss gives heads. Let $\mathcal{A} = \{A_1, A_2, \dots, A_n\}$. What is $\sigma(\mathcal{A})$? Indeed, $\sigma(\mathcal{A})$ is the power set of the sample space.

**** Tossing a Coin Forever

The sample space is $\Omega = \{0, 1\}^\N$. Let $A_i$ denote the event that the $i^\text{th}$ toss gives heads. Let $\mathcal{A} = \{A_1, A_2, \dots \}$. What is $\sigma(\mathcal{A})$? Counter-intuitively, it is not the power set of the sample space.
It is a strict subset of the power set.

**** Motion on $\mathbb{R}$

The sample space is $\Omega = \R$. Let A be the event where the position is strictly between $a, b$, $a < b$. Let $\mathcal{A} = \{(a, b) | a < b, a, b \in \R \}$. What is $\sigma(\mathcal{A})$? Non-trivially, $\sigma(\mathcal{A}) \subsetneq 2^\R$.

*** Borel $\sigma$ -algebra

\begin{definition}[Borel $\sigma$-algebra]
The $\sigma$-algebra
$$
B(\R) = \sigma(\{ (a, b) | a, b \in \mathbb{R} \})
$$
is called the Borel $\sigma$-algebra on $\R$.
\end{definition}

\begin{proposition}[$B(\R)$ is rich]
The Borel $\sigma$-algebra $B(\R)$ on $\R$ is generated is generated by each of the following collection
\begin{itemize}
\item $\mathcal{A}_1 = \{ (a, b) \mid a, b \in \R \}$,
\item $\mathcal{A}_2 = \{ [a, b] \mid a, b \in \R \}$,
\item $\mathcal{A}_3 = \{ [a, b) \mid a, b \in \R \}$,
\item $\mathcal{A}_4 = \{ (a, b] \mid a, b \in \R \}$,
\item $\mathcal{A}_5 = \{ (a, \infty) \mid a, b \in \R \}$,
\item $\mathcal{A}_6 = \{ [a, \infty) \mid a, b \in \R \}$,
\item $\mathcal{A}_7 = \{ (-\infty, b) \mid a, b \in \R \}$,
\item $\mathcal{A}_8 = \{ (-\infty, b] \mid a, b \in \R \}$.
\end{itemize}
In particular, $B(\R)$ includes all intervals and singletons. We say here that
$$
B(\R) = \sigma(\mathcal{A}_1) = \dots = \sigma(\mathcal{A}_8).
$$
\end{proposition}

\begin{proof}
Let's show that
$$
\sigma(\mathcal{A}_1) \subset \sigma(\mathcal{A}_3) \subset \sigma(\mathcal{A}_2) \subset \sigma(\mathcal{A}_4) \subset \sigma(\mathcal{A}_8) \subset \sigma(\mathcal{A}_5) \subset \sigma(\mathcal{A}_6) \subset \sigma(\mathcal{A}_7) \subset \sigma(\mathcal{A}_1).
$$
First, we prove that $\sigma(\mathcal{A}_1) \subset \sigma(\mathcal{A}_3)$. Suppose $A \in \mathcal{A}_1$. We first show that $A \in \sigma(\mathcal{A}_3)$. Note that $A = (a, b)$ for some $a, b \in \R$ with $a < b$. Then,
$$
A = (a, b) = \cup_{n \in \N} [a + \frac{1}{n}, b).
$$
Since each $[a + \frac{1}{n}, b)$ is in $\mathcal{A}_3$, the countable union is in $\sigma(\mathcal{A}_3)$. We now have shown that $\mathcal{A}_1 \subset \sigma(\mathcal{A}_3)$. To conclude that $\sigma(\mathcal{A}_1) \subset \sigma(\mathcal{A}_3)$, we use the following lemma.
The rest of the proof is left as an exercise for the readers.
\end{proof}

\begin{lemma}
Let $\mathcal{A}$ be a collection of subset of $\Omega$ and $\mathcal{F}$ a $\sigma$ -algebra on $\Omega$. Then,
$$
\mathcal{A} \subset \mathcal{F} \implies \sigma(\mathcal{A}) \subset \mathcal{F}.
$$
\end{lemma}

\begin{proof}
Since $\mathcal{A} \in \mathcal{F}$, $\mathcal{F}$ is a $\sigma$-algebra on $\Omega$ containing $\mathcal{A}$. So, it is larger than the smallest $\sigma$-algebra containing $\mathcal{A}$. This is precisely $\sigma(A) \subset \mathcal{F}$.
\end{proof}

*** Tracing

\begin{proposition}[Trace]
Let $(\Omega, \mathcal{F})$ be a measurable space and $A \subset \Omega$ a nonempty set. The collection
$$
\mathcal{A} := \{A \cap F \mid F \in \mathcal{F}\}
$$
is a $\sigma$-algebra. The set is called the trace of $\mathcal{F}$ on $A$.
\end{proposition}
The application is $(\Omega, \mathcal{F}) = (\R, B(\R))$. Let $A = [0, 1]$. Then,
$$
\mathcal{A} = \{ [0, 1] \cap B \mid B \in B(\R)  \}
$$
is called the Borel $\sigma$ -algebra on $[0, 1]$, denoted $B([0, 1])$. Similarly, we may define $B(A)$ for every $A \subset \R$.

\begin{proof}
Let's prove that $\mathcal{A}$ is a $\sigma$-algebra on $A$.
\begin{itemize}
\item $A  = A \cup \Omega \in \mathcal{A}$ since $\Omega \in \mathcal{F}$.
\item Let $B \in \mathcal{A}$. Then, $B = A \cap F$ for some $F \in \mathcal{F}$. So $A \setminus B = A \cap B^c = A \cap (A \cap F)^c = A \cap (A^c \cup F^c) = (A \cap A^c) \cup (A \cap F^c) = A \cap F^c \in \mathcal{A}$.
\item Let $B_1, B_2, \dots \in \mathcal{A}$. So $B_1 = A \cap F_1, B_2 = A \cap F_2, \dots$ for some $F_1, F_2, \dots \in \mathcal{F}$. So, $\cup_{i=1}^\infty B_i = \cup^\infty_{i=1} (A \cap F_i) = A \cap (\cup^\infty_{i=1} F_i) \in \mathcal{A}$.
\end{itemize}
So $\mathcal{A}$ is a $\sigma$-algebra on $A$.
\end{proof}

** Monotone Class Theorem

\begin{definition}[Dynkin system]
Let $\Omega \ne \emptyset$ and $\mathcal{D}$ a collection of subsets of $\Omega$. $\mathcal{D}$ is called a Dynkin system ($\lambda$-system) on $\Omega$ if
\begin{itemize}
\item $\Omega \in \mathcal{D}$
\item $A \in \mathcal{D} \implies A^c \in \mathcal{D}$
\item If $A_1, A_2, \dots \in \mathcal{D}$ are disjoint, then $\cup_{i \in \N} A_i \in \mathcal{D}$
\end{itemize}
\end{definition}

If you have a $\sigma$ -algebra, it is a Dynkin system. The converse fails in general. A Dynkin system cannot handle properly intersection of sets.
Why don't we define another structure just for the purpose of dealing with intersections.

\begin{definition}[Dynkin system]
Let $\Omega \ne \emptyset$ and $\mathcal{P}$ a collection of subsets of $\Omega$. $\mathcal{P}$ is called a $\pi$ system on $\Omega$ if it is closed under finite intersections:
$$
A_1, \dots, A_n \in \mathcal{P} \implies \bigcap_{i=1}^n A_i \in \mathcal{P}.
$$
\end{definition}

\begin{proposition}
Let $\Omega \ne \emptyset$ and $\mathcal{F}$ a collection of subsets of $\Omega$. $\mathcal{F}$ is a $\sigma$-algebra if and only if it is a $\pi$-system and a $\lambda$-system.
\end{proposition}

\begin{proof}
Suppose that $\mathcal{F}$ is a $\sigma$-algebra. Then, it is clearly a Dynkin system. It is also a $\pi$-system as shown before.
Conversely, supppose $\mathcal{F}$ is a $\pi$-system and a Dynkin system. To show $\mathcal{F}$ is a $\sigma$-algebra, we only need to check it is closed under countable unions.
To that end, let $A_1, A_2, \dots \in \mathcal{F}$.
Set $B_1 := A_1, B_2 := A_2 \setminus A_1, B_3 := A_3 \setminus (A_1 \cup A_2), \dots, B_{n + 1} := A_{n + 1} \setminus (\cup_{i=1}^n A_i)$.
Note that $B_i$'s are in $\mathcal{F}$ since
$$
B_{n + 1} = A_{n + 1} \cap (\cup_{i = 1}^n A_i)^c = A_{n + 1} \cap (\cap_{i = 1}^n A_i^c).
$$
Since $A_i \in \mathcal{F}$ and $\mathcal{F}$ is Dynkin system, $A_i^c \in \mathcal{F}$. Then, by the property of $\pi$-system, $B_i$'s are in $\mathcal{F}$.
Observe that by contruction, $B_i$'s are disjoint. So, by the definition of Dynkin sysmtem,
$$
\bigcup_{i=1} A_i = \bigcup_{i=1} B_i \in \mathcal{F}.
$$
So, $\mathcal{F}$ is a $\sigma$-algebra.
\end{proof}

$\mathcal{A} = \{ (a, b) \mid a, b \in \R \}$ is a $\pi$ -system. This $\pi$ -system is much simpler than the Borel $\sigma$ -algebra $B(\R)$.
The idea is that when proving a statement about $B(\R)$, can we "reduce" the proof to a statement about $\mathcal{A}$?

\begin{theorem}[Monotone class theorem]
Let $\Omega \ne \emptyset$. Let $\mathcal{P}$ be a $\pi$-system and $\mathcal{D}$ be a Dynkin system on $\Omega$. Then,
$$
\mathcal{P} \subset \mathcal{D} \implies \sigma(\mathcal{P}) \subset \mathcal{D}.
$$
\end{theorem}

Suppose you have to prove a statement for every set in $\sigma(\mathcal{P})$. Follow this recipe
\begin{itemize}
\item Show the statement for every set in $\mathcal{P}$
\item Show that the collection of all sets satisfying this property is a Dynkin system $\mathcal{D}$
\item So $\mathcal{P} \subset \mathcal{D}$, use the theorem to conclude that $\sigma(\mathcal{D}) \subset \mathcal{D}$. So the statement holds for every set in $\sigma(\mathcal{P})$.
\end{itemize}

An arbitrary intersection of $\sigma$ -algebra is a $\sigma$ -algebra. The same is true for Dynkin systems and $\pi$ -systems.
So, given a collection $\mathcal{A}$ of subsets of $\Omega$, we can talk about $\sigma(\mathcal{A})$, the smallest $\sigma$ -algebra contraining $\mathcal{A}$.
We can talk about $\lambda(\mathcal{A})$, the smallest Dynkin system containing $\mathcal{A}$, and $\pi(\mathcal{A})$, the smallest $\pi$ -system contraining $\mathcal{A}$.
In particular, if $\mathcal{D}$ is a Dynkin system,
$$
\mathcal{A} \subset \mathcal{D} \implies \lambda(\mathcal{A}) \subset \mathcal{D}.
$$

Suppose the Monotone class theorem holds true. Let's take $\mathcal{D} = \lambda(\mathcal{P})$ as a special case since $\mathcal{P} \lambda(\mathcal{P})$.
By the theorem, we get
$$
\sigma(\mathcal{P}) \subset \lambda(\mathcal{P}).
$$
But on the other hand, $\lambda(\mathcal{P}) \subset \sigma(\mathcal{P})$, since $\sigma(\mathcal{P})$ is a Dynkin system and
$$
\mathcal{A} \subset \mathcal{D} \implies \lambda(\mathcal{A}) \subset \mathcal{D}.
$$
So, we get
$$
\lambda(\mathcal{P}) = \sigma(\mathcal{P}).
$$
Suppose conversely that $\lambda(\mathcal{P}) = \sigma(\mathcal{P})$ holds. Let $\mathcal{D}$ be a Dynkin system containing $\mathcal{P}$.
So, $\mathcal{P} \subset \mathcal{D}$ implies $\lambda(\mathcal{P}) \subset \mathcal{D}$. But by the assumption, $\sigma(\mathcal{P}) = \lambda(\mathcal{P}) \subset \mathcal{D}$.
So, the claim of the theorem holds.
This results, or simplification of the theorem tells us that the Dynkin system and the $\sigam$ -algebra generated by a $\pi$ -system coincide.
We now prove that
$$
\lambda(\mathcal{P}) = \sigma(\mathcal{P}).
$$
\begin{proof}
First of all, $\lambda(\mathcal{P}) \subset \sigma(\mathcal{P})$ follows from the fact that $\sigma(\mathcal{P})$ is a Dynkin system containing $\mathcal{P}$.
Now, we show that $\sigma(\mathcal{P}) \subset \lambda(\mathcal{P})$. To show this, it is sufficient to show that $\lambda(\mathcal{P})$ is a $\sigma$-algebra.
This is because
$$
\mathcal{P} \subset \lambda(\mathcal{P}) \implies \sigma(\mathcal{P}) \subset \lambda(\mathcal{P}).
$$
To prove $\lambda(\mathcal{P})$ is a $\sigma$-algebra, by the ``$\sigma = \pi + \lambda$'' theorem, it is sufficient to show that $\lambda(\mathcal{P})$ is a $\pi$-system.
Let's show that $A, B \in \mathcal{P} \implies A \cap B \in \lambda(\mathcal{P})$. We first show that
$$
A, B \in \mathcal{P} \implies A \cap B \in \lambda(\mathcal{P}).
$$
Since $\mathcal{P}$ is a $\pi$-system, $A \cap B \in \mathcal{P} \subset \lambda(\mathcal{P})$. Now, we show that
$$
A \in \mathcal{P}, B \in \lambda(\mathcal{P}) \implies A \cap B \in \lambda(\mathcal{P}).
$$
Let us fix $A \in \mathcal{P}$ and define
$$
\mathcal{B}_1 := \{ B \subset \Omega \mid A \cap B \in \lambda(\mathcal{P}) \}.
$$
If we can show that $\lambda(\mathcal{P}) \subset \mathcal{B}_1_$, then we are done.
First, $\mathcal{P} \subset \mathcal{B}_1$. We now need to show that $\mathcal{B}_1$ is a Dynkin system, so that we can show that
$$
\mathcal{P} \subset \mathcal{B}_1 \implies \lambda(\mathcal{P}) \subset \mathcal{B}_1.
$$
The proof is left as an exercise for the readers (check the definition).
Now, what remain for us to show is that
$$
A, B \in \lambda(\mathcal{P}) \implies A \cap B \in \lambda(\mathcal{P}).
$$
Let use fix $A \in \lambda(\mathcal{P})$ and define
$$
\mathcal{B}_2 = \{ B \subset \Omega \mid A \cap B \in \lambda(\mathcal{P}) \}.
$$
If we can show $\lambda(\mathcal{P}) \subset \mathcal{B}_2$, then we are done.
First, $\mathcal{P} \subset \mathcal{B}_2$, by the previous step. To conclude, it is sufficient to show that $\mathcal{B}_2$ is a Dynkin system.
The rest of the proof is left as an exercise for the readers.
\end{proof}

** Probability and Measure Spaces

* Random Variables
* Random Vectors
* Conditioning
* Infinite Collections of Random Variables
* Convergence
